language: node_js
node_js:
  - "0.10.40"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g coffee-script"
  - "npm install -g spacejam"
  - "export PATH=$PATH:$HOME/.meteor"

script: "spacejam test-packages ./"
